package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"context"
	"fmt"

	"github.com/NeurologiaLogic/gochat/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input *model.NewUser) (*model.User, error) {
	return &model.User{
		ID:       "F12123",
		Username: input.Username,
		Email:    input.Email,
		Password: input.Password,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, password string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, username string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Logout - logout"))
}

// JoinRoom is the resolver for the joinRoom field.
func (r *mutationResolver) JoinRoom(ctx context.Context, username string, roomName string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: JoinRoom - joinRoom"))
}

// LeaveRoom is the resolver for the leaveRoom field.
func (r *mutationResolver) LeaveRoom(ctx context.Context, username string, roomName string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: LeaveRoom - leaveRoom"))
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, username string, roomName string, message string) (*model.Message, error) {
	panic(fmt.Errorf("not implemented: SendMessage - sendMessage"))
}

// GetRooms is the resolver for the getRooms field.
func (r *queryResolver) GetRooms(ctx context.Context, username string) ([]*model.ChatRoom, error) {
	panic(fmt.Errorf("not implemented: GetRooms - getRooms"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *mutationResolver) GetRooms(ctx context.Context, username string) ([]*model.ChatRoom, error) {
	panic(fmt.Errorf("not implemented: GetRooms - getRooms"))
}
