// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChatRoom struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Members   []*User    `json:"members,omitempty"`
	Messages  []*Message `json:"messages,omitempty"`
	CreatedAt string     `json:"createdAt"`
}

type Message struct {
	ID        string    `json:"id"`
	Text      string    `json:"text"`
	Sender    *User     `json:"sender"`
	ChatRoom  *ChatRoom `json:"chatRoom"`
	CreatedAt string    `json:"createdAt"`
}

type User struct {
	ID       string      `json:"id"`
	Username string      `json:"username"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
	Online   *bool       `json:"online,omitempty"`
	Rooms    []*ChatRoom `json:"rooms,omitempty"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
